-- MVP schema for Supabase/PostgreSQL.
-- modelo_fisico.sql is MySQL syntax and cannot be executed directly in Supabase.

create table if not exists public.perfil_artista (
  id_perfil_artista bigint generated by default as identity primary key,
  nome_artistico varchar(150),
  bio_profissional text,
  foto_principal varchar(255),
  data_inicio_atividade date,
  reputacao_score double precision default 0 not null,
  verificado boolean default false not null,
  ativo boolean default true not null,
  criado_em timestamptz default now() not null,
  editado_em timestamptz default now() not null,
  generos_musicais jsonb default '[]'::jsonb not null
);

create table if not exists public.banda (
  id_banda bigint generated by default as identity primary key,
  nome_banda varchar(150) not null,
  descricao text not null,
  data_formacao date not null,
  foto_principal varchar(255),
  reputacao_score double precision default 0 not null,
  verificado boolean default false not null,
  ativo boolean default true not null,
  criado_em timestamptz default now() not null,
  editado_em timestamptz default now(),
  generos_musicais jsonb default '[]'::jsonb not null
);

create table if not exists public.espaco_cultural (
  id_espaco_cultural bigint generated by default as identity primary key,
  nome_espaco varchar(150) not null,
  descricao text not null,
  site varchar(255),
  horario_funcionamento jsonb default '{}'::jsonb not null,
  capacidade_maxima integer,
  publico boolean default true not null,
  verificado boolean default false not null,
  criado_em timestamptz default now() not null,
  editado_em timestamptz default now() not null,
  ativo boolean default true not null,
  endereco text
);

create table if not exists public.evento (
  id_evento bigint generated by default as identity primary key,
  nome_evento varchar(150) not null,
  descricao text not null,
  data_evento date not null,
  hora_inicio time not null,
  hora_fim time,
  data_cadastro timestamptz default now() not null,
  data_moderacao timestamptz,
  observacoes_moderador text,
  url_cartaz varchar(255),
  link_ingresso varchar(255),
  reputacao_score double precision default 0 not null,
  ativo boolean default true not null,
  verificado boolean default false not null,
  preco_ingresso numeric(10, 2) default 0 not null,
  fk_id_espaco_cultural bigint not null references public.espaco_cultural(id_espaco_cultural)
);

create index if not exists idx_evento_data_ativo on public.evento (data_evento, ativo);
create index if not exists idx_artista_ativo_verificado on public.perfil_artista (ativo, verificado);
create index if not exists idx_espaco_ativo_verificado on public.espaco_cultural (ativo, verificado);
create index if not exists idx_banda_nome on public.banda using gin (to_tsvector('simple', nome_banda));

alter table public.perfil_artista enable row level security;
alter table public.banda enable row level security;
alter table public.espaco_cultural enable row level security;
alter table public.evento enable row level security;

create policy "conteudo ativo pode ser lido publicamente" on public.perfil_artista for select using (ativo = true and verificado = true);
create policy "bandas ativas podem ser lidas publicamente" on public.banda for select using (ativo = true);
create policy "espacos ativos podem ser lidos publicamente" on public.espaco_cultural for select using (ativo = true and verificado = true);
create policy "eventos ativos podem ser lidos publicamente" on public.evento for select using (ativo = true);